CC=gcc
OBJ=playagain1.o playagain2.o playagain3.o
CFLAGS=-g3
play_again:
play_again1:
play_again2:
play_again3:
play_again4:
.PHONY:clean
clean:
	-rm -rf $(OBJ)
	-rm -rf play_again play_again1 play_again2 play_again3 play_again4
