CC=gcc
CFLAGS=-g3 -Wall
OBJ=
forkdemo1:
forkdemo2:
forkdemo3:
waitdemo1:
waitdemo2:
exec1:
psh1:
psh2:
.PHONY:clean
clean:
	-rm -rf *.o
	-rm -rf forkdemo1 forkdemo2 forkdemo3
	-rm -rf exec1
	-rm -rf psh1 psh2
	-rm -rf waitdemo1 waitdemo2 
