CC=gcc
OBJ=who1.o 
CFLAGS=-g3 -Wall
who:
who1:
who2:
who3:	
who4: 
cp1:
n2n:
lseek:	
myod:
myhead:
mylast:
mycurses:
.PHONY:clean
clean:
	-rm -rf *.o
	-rm who1 who2 cp1 n2n lseek who3 who4 who5 myod myhead mylast mycurses
